import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { useQuery, gql, useLazyQuery } from "@apollo/client";
import styles from "../styles/Home.module.css";

export const QUERY_METADATA = gql`
  query Query($system: String!, $sap_user: String!, $sap_password: String!) {
    getMetadata(
      system: $system
      sap_user: $sap_user
      sap_password: $sap_password
    ) {
      content
    }
  }
`;

export default function Home() {
  /* const { data, loading, error } = useQuery(QUERY_METADATA, {
    variables: {
      system:
        "http://vhcalnplci.dummy.nodomain:8000/sap/opu/odata/sap/ZSAP_TOOLS_CORE_SRV/",
      sap_user: "developer",
      sap_password: "Manolete",
    },
  });*/
  const [resultado, setResultado] = useState("");

  const [getMetadata, { loading, data }] = useLazyQuery(QUERY_METADATA, {
    onError: (error) => {
      console.log("erroor");
    },
    onCompleted: (data) => {
      setResultado(data.getMetadata.content);
      console.log("completed");
    },
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Pruebas de GraphQL</h1>
        <button
          onClick={() => {
            getMetadata({
              variables: {
                system:
                  "http://vhcalnplci.dummy.nodomain:8000/sap/opu/odata/sap/ZSAP_TOOLS_CORE_SRV/",
                sap_user: "",
                sap_password: "",
              },
            });
          }}
        >
          Leer
        </button>
        <p className={styles.description}>
          {loading && <p>Leyendo los datos....</p>}
          {!loading && <p>Datos leídos</p>}
        </p>
        <div className={styles.grid}>{!loading && resultado}</div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
