import Head from "next/head";
import Image from "next/image";
import { useQuery, gql } from "@apollo/client";
import styles from "../styles/Home.module.css";

const QUERY = gql`
  query Query {
    getAll {
      _id
      mueble
      material
    }
  }
`;
export default function Home() {
  const { data, loading, error } = useQuery(gql`
    query Query {
      getAll {
        _id
        mueble
        material
      }
    }
  `);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Pruebas de GraphQL</h1>

        <p className={styles.description}>
          {loading && <p>Leyendo los datos....</p>}
          {!loading && <p>Datos leídos</p>}
        </p>
        <div className={styles.grid}>
          <ul>
            {!loading &&
              data.getAll.map((row) => <li key={row._id}>{row.mueble}</li>)}
          </ul>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
